# CONFIGURATION FILE

# MODIFY THE NAME OF THE CURRENCY
currency-name: "$"

# MODIFY THE SCOREBOARD
scoreboard-title: "&2&lTowns:"
scoreboard-entry-colour: "&6"

# STARTING AMOUNT - this is the amount of money a player will require to start a town
town-start-amount: 100.0

# MODIFY THE MESSAGES
# placeholders: none
message-already-in-town: "&cYou are already part of a town! You need to do /town leave, then /town join <town name>"
message-invitee-in-town: "&cThat player is already in this town"
message-not-in-town: "&cYou are not in a town!"
message-town-exists: "&cA town with that name already exists!"
message-town-not-exists: "&cA town with that name does not exist!"
message-no-permission: "&cYou do not have permission to do this!"
message-player-no-exist: "&cThat player does not exist!"
message-player-not-online: "&cThat player is not online!"
message-use-real-number: "&cYou need to enter a real non-negative number!"
message-no-invite: "&cYou do not have an invite for that town!"
message-item-not-sellable: "&cYou can't sell this item!"
message-insufficient-funds: "&cYou do not have enough money!"
message-shop-in-use: "&cSomeone else is using that shop right now!"
message-disband-town: "&aYour town was disbanded successfully!"
# placeholders: %money%
message-check-balance: "&aYour balance is &e%money%"
# placeholders: %town%
message-town-created: "&aYou successfully created town &e%town%"
message-town-joined: "&aYou successfully joined town &e%town%"
message-town-left: "&aYou successfully left town &e%town%"
# placeholders: %player%, %money%
message-set-player-balance: "&aYou set &e%player% &ato &e%money%"
message-check-balance-other: "&a%player%'s balance is &e%money%"
# placeholders: %amount%, %currency%, %town%
message-set-town-money: "&e%town% &awas set to &e%amount% %currency%&a!"
message-send-town-money: "&aYou sent &e%amount% %currency% &ato &e%town%"
message-deposit-item: "&aYou successfully deposited %currency%%amount% to your %town%"
message-withdraw-item: "&aYou successfully withdrew %currency%%amount% from your %town%"
# placeholders: %amount%, %item%, %currency%, %money%
message-sell-item: "&aYou successfully sold &e%amount%&ax&e%item% &afor &e%currency%%money%!"
message-buy-item: "&aYou successfully bought &e%amount%&ax&e%item% &afor &e%currency%%money%!"

# MODIFY SELLABLE ITEMS
#key: ITEM_NAME;price
sellable-items:
  - COAL_ORE;5
  - IRON_ORE;5
  - GOLD_ORE;5
  - DIAMOND_ORE;5
  - REDSTONE_ORE;5
  - LAPIS_ORE;5
  - ANCIENT_DEBRIS;5
  - STRING;6
  - FEATHER;7
  - BLAZE_ROD;4
  - SPIDER_EYE;3
  - SULPHUR;5
  - ROTTEN_FLESH;4
  - ENDER_PEARL;4
  - EMERALD;4
  - TOTEM_OF_UNDYING;4
  - GHAST_TEAR;3
  - PORKCHOP;5
  - COOKED_PORKCHOP;5
  - MAGMA_CREAM;4
  - ARROW;5
  - BONE;5
  - SLIME_BALL;5
  - GOLD_NUGGET;4
  - WHEAT;5
  - BEETROOT;4
  - CARROTS;4
  - POTATOES;3